//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationProject1.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_uk_UA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_uk_UA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EducationProject1.Localization.Resources.Resources.uk-UA", typeof(Resources_uk_UA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити фігуру.
        /// </summary>
        public static string ButtonsGroupHeader {
            get {
                return ResourceManager.GetString("ButtonsGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попередження.
        /// </summary>
        public static string CaptionWarning {
            get {
                return ResourceManager.GetString("CaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коло.
        /// </summary>
        public static string CircleName {
            get {
                return ResourceManager.GetString("CircleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колізія.
        /// </summary>
        public static string Collision {
            get {
                return ResourceManager.GetString("Collision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} між {1} та {2} в точці: {3}.
        /// </summary>
        public static string CollisionMessage {
            get {
                return ResourceManager.GetString("CollisionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string FileMenuItem {
            get {
                return ResourceManager.GetString("FileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щоб зберегти фігури в файл необхідно спочатку додати хоча б одну.
        /// </summary>
        public static string MessageAddAtLeastOneFigure {
            get {
                return ResourceManager.GetString("MessageAddAtLeastOneFigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректний формат файлу.
        /// </summary>
        public static string MessageIncorrectFileSignature {
            get {
                return ResourceManager.GetString("MessageIncorrectFileSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректна версія файлу збереження.
        /// </summary>
        public static string MessageIncorrectSaveFileVersion {
            get {
                return ResourceManager.GetString("MessageIncorrectSaveFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рухатися.
        /// </summary>
        public static string MoveFigureButtonText {
            get {
                return ResourceManager.GetString("MoveFigureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкрити.
        /// </summary>
        public static string OpenMenuItem {
            get {
                return ResourceManager.GetString("OpenMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямокутник.
        /// </summary>
        public static string RectangleName {
            get {
                return ResourceManager.GetString("RectangleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string SaveMenuItem {
            get {
                return ResourceManager.GetString("SaveMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть файл збереження.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть місце для зберігання файлу.
        /// </summary>
        public static string SelectPlaceForSavingFile {
            get {
                return ResourceManager.GetString("SelectPlaceForSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рухати всі.
        /// </summary>
        public static string StartAllFigureButtonText {
            get {
                return ResourceManager.GetString("StartAllFigureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зупинити усі.
        /// </summary>
        public static string StopAllFigureButtonText {
            get {
                return ResourceManager.GetString("StopAllFigureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп.
        /// </summary>
        public static string StopFigureButtonText {
            get {
                return ResourceManager.GetString("StopFigureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трикутник.
        /// </summary>
        public static string TriangleName {
            get {
                return ResourceManager.GetString("TriangleName", resourceCulture);
            }
        }
    }
}
